### ISSUE TITLE
Create program for reading REAC db

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/HUD#17]

**Comment by katyaabaz** [comment]
Started a new branch in the HUD repository addressing this enhancement. I followed the format of the MFIS file and had two question about the REAC_read_update_file.sas program. Paused, waiting for feedback.

**Comment by katyaabaz** [comment]
@mcohenui I talked to Peter before Thanksgiving about using a key for this from the old access database, but haven't worked on it since then.

**Comment by katyaabaz** [comment]
@ptatian I had forgotten to merge a pull request after you OK'ed this program, so I just did that and copied the program to batch submit on the L: drive. After batch submitting, the datasets were produced correctly without errors, but the file_info statement created issues because the REAC dataset doesn't contain any numeric variables. Somehow this wasn't an issue when I ran locally, but Proc means just didn't print. Proc means couldn't find any analysis variables so there are a couple of errors, shown in the log here: L:\Libraries\HUD\Prog\REAC\REAC_2016_09.txt

May need to edit REAC_2016_09.sas locally in the event that the errors are fixable. Again, I think the datasets are OK, just the checks after the datasets are produced aren't working. 
CC: @mcohenui

**Comment by ptatian** [comment]
Thanks, Katya. Yes, this is a [known issue](https://github.com/ptatian/uiautos/issues/2) with the metadata system. It doesn't usually come up but obviously did here. Something I need to deal with so sorry for any concern. 
I agree that it seems not to have affected the actual data sets themselves.

**Comment by katyaabaz** [comment]
@ptatian Great! I'll close this issue and try and document where I left off in the PresCat library.
