### ISSUE TITLE
Fix MFIS program to work around missing Premise ID

### ISSUE THREAD

**Issue by katyaabaz** [NeighborhoodInfoDC/HUD#32]
Premise ID column is no longer included in MFIS data, remove from input statement.

**Comment by ptatian** [comment]
The Premise_id is not needed for the main Catalog matching process. It only is used if there is a new loan issued to an existing property. So, it should be possible to do the Catalog update even if Premise_id is missing. The only thing is you may end up with more loans that don't get matched to a project. 

I would still create a blank Premise_id field in the HUD.Mfis_* file, because that way you don't need to change any of the PresCat update programs (at least for now). So, as you said, the input statement needs to be modified for the new file format and a blank Premise_id added to the file. 

Let me know if that makes sense.

**Comment by katyaabaz** [comment]
I tried creating a blank Premise ID in the raw data file for now, but then when I ran the updating program, the subsidy_nonmatch excel file was showing 132 properties instead of the usual number around 50. Is that OK? I figured just to leave it alone because I wasn’t sure what the consequences of that were.

**Comment by ptatian** [comment]
Yes, this is what I meant by there would be more unmatched loans, but it's a larger number than I thought. Before, the program would use the Premise_id to match the new loans to existing properties and create a new subsidy record. Now we don't have that ability unless we figure out some other means for matching the loan to the property. It could be done by hand, or perhaps the geocoding macro could be used. We could geocode the addresses in the MFIS file to add the parcel SSL, and then use that to match the loans to projects.

**Comment by ptatian** [comment]
I think it's the right call for now to go ahead with the update as is and try to fix this later. 
So, you didn't change the code but changed the MFIS input data set? That's OK, but then you'll have to do that every time because it sounds like HUD is not going to restore that field. Probably worth thinking about changing the code as a permanent fix.

**Comment by ptatian** [comment]
This is really part of a pre-existing problem that needs to be addressed at some point. There are a number of MFIS updates to projects in the Catalog that aren't being made because we can't connect the MFIS record to the Catalog project record. In addition, there may be some entirely new projects, not currently in the Catalog, that need to be added. All of those are the things listed in the L:\Libraries\PresCat\Prog\Updates\Update_MFIS_2016_04_subsidy_nonmatch.xls file. 
Ideally, we would create a process that allows us to deal with all of the subsidies listed in the *_subsidy_nomatch.xls files.
